# Generated by Django 2.0.2 on 2019-03-31 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('n2t', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='title',
            new_name='NAME',
        ),
    ]
