# Generated by Django 2.0.2 on 2019-02-26 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('n2t', '0003_auto_20190226_0045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='TIME',
            new_name='COORDINATE',
        ),
    ]
