# Generated by Django 2.0.2 on 2019-02-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TIME', models.PositiveIntegerField()),
                ('H1G', models.TextField()),
            ],
        ),
    ]
