from django.db import models

class Note(models.Model):
	TIME = models.PositiveIntegerField()
	H1G = models.BooleanField()
	H1F = models.BooleanField()
	H1E = models.BooleanField()
	H1D = models.BooleanField()
	H1C = models.BooleanField()
	M1B = models.BooleanField()
	M1A = models.BooleanField()
	M1G = models.BooleanField()
	M1F = models.BooleanField()
	M1E = models.BooleanField()
	M1D = models.BooleanField()
	M1C = models.BooleanField()
	L1B = models.BooleanField()
	L1A = models.BooleanField()
	L1G = models.BooleanField()
	L1F = models.BooleanField()
	L1E = models.BooleanField()
	L1D = models.BooleanField()
	L1C = models.BooleanField()
	L2B = models.BooleanField()
	L2A = models.BooleanField()
	L2G = models.BooleanField()
	L2F = models.BooleanField()
