from django.db import models

class Note(models.Model):
	COORDINATE = models.PositiveIntegerField()
	title = models.CharField(max_length=128)
	H1G = models.BooleanField(default=0)
	H1F = models.BooleanField(default=0)
	H1E = models.BooleanField(default=0)
	H1D = models.BooleanField(default=0)
	H1C = models.BooleanField(default=0)
	M1B = models.BooleanField(default=0)
	M1A = models.BooleanField(default=0)
	M1G = models.BooleanField(default=0)
	M1F = models.BooleanField(default=0)
	M1E = models.BooleanField(default=0)
	M1D = models.BooleanField(default=0)
	M1C = models.BooleanField(default=0)
	L1B = models.BooleanField(default=0)
	L1A = models.BooleanField(default=0)
	L1G = models.BooleanField(default=0)
	L1F = models.BooleanField(default=0)
	L1E = models.BooleanField(default=0)
	L1D = models.BooleanField(default=0)
	L1C = models.BooleanField(default=0)
	L2B = models.BooleanField(default=0)
	L2A = models.BooleanField(default=0)
	L2G = models.BooleanField(default=0)
	L2F = models.BooleanField(default=0)
